### ISSUE TITLE
class-autocompletion doesn't work properly with created classes.

### ISSUE THREAD

**Issue by svaningelgem** [efekos/Classes#3]
We created a class "Knight". But when we type `/class Kn`, I would expect the "Knight" option to be on top. However, it's not:
![image](https://github.com/efekos/Classes/assets/199434/c1fc32da-391d-4c52-af02-e069e9c5c28a)

**Comment by efekos** [comment]
That is because `/class choose`, `/class create` and `/class leave` are existing commands. You can add a space after `/class Knight` to see auto-completion of class related commands, such as `/class Knight modifier list`

**Comment by svaningelgem** [comment]
Yes, that works, but it's not completing on `Knight`. So I'd classify that as a bug 😉

**Comment by efekos** [comment]
'Knight' not being on top is probably something wrong about the command library I'm using. I'm currently working on an update to switch to a new command library that uses Brigaider, hopefully fixing issues like this. But I can't really do that much about it at the moment since current codebase is a lot different than the latest version.

**Comment by svaningelgem** [comment]
FYI: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/command/TabCompleter.html
